#!/bin/bash

set -e

echo "Creating image directories if needed..."
mkdir -p /images/artists \
  && mkdir -p /images/avatars \
  && mkdir -p /images/covers \
  && mkdir -p /images/playlists \
  && mkdir -p /images/radio-stations \
  && chown  www-data:www-data /images/*

# Change to program root directory.
cd /var/www/html

# Set X-SendFile path
if [[ "$MEDIA_PATH" != "/music" ]]; then
    echo "Updating XSendFilePath to $MEDIA_PATH"
    sed --regexp-extended --in-place "s|XSendFilePath.+$|XSendFilePath $MEDIA_PATH|" /etc/apache2/sites-available/000-default.conf
fi

# Run the next entrypoint in the chain.
echo "running docker-php-entrypoint with arguments $@"
docker-php-entrypoint $@
